from common import *

ROWS = [
("PRV-HR-A09-RMS", "Art. 9(1)-(5)",
 "Run a documented, continuous, lifecycle risk management system: identify foreseeable risks to health, safety and fundamental rights (intended use AND reasonably foreseeable misuse), use post-market data, adopt targeted measures, and judge residual risk acceptable per hazard and overall.",
 PRV, HR, HR_DATES, "Date moved only",
 "main-body AI risk assessment and risk treatment requirements; A.6.1.2 objectives for responsible development; A.6.1.3 processes for responsible design and development. Intent: a repeatable AI-risk process with treatment and residual-risk acceptance.", P,
 "main-body information-security risk assessment and treatment requirements - covers the security slice only.", A,
 "MAP 5.1; MEASURE 1.1; MANAGE 1.2; MANAGE 1.3; MANAGE 1.4", P,
 "ISO risk = effect of uncertainty on the organisation's objectives; Art. 9 risk = harm to health, safety, fundamental rights. A certificate does not show the risk criteria are rights-anchored. Art. 9(3) scoping, per-hazard AND overall residual-risk acceptability (9(5)), and foreseeable-misuse analysis are not explicit in ISO. Certification auditors do not test against Art. 9.",
 "Re-base AIMS risk criteria on Art. 9(2) harm categories; keep per-hazard residual-risk records; feed the /register/ layer. NIST MANAGE 1.4 (residual risk to end users) is the closest single outcome to Art. 9(5).",
 "prEN 18228 (AI risk management): public enquiry closed 30 Jul 2026, rejected by a majority of national standards bodies; comment resolution due Nov 2026. Not cited in the OJ."),

("PRV-HR-A09-TEST", "Art. 9(6)-(8)",
 "Test the system to find the most appropriate risk measures: consistent performance for intended purpose, against metrics and probabilistic thresholds defined in advance, at any point in development and in any event before placing on the market (real-world testing optional under Art. 60).",
 PRV, HR, HR_DATES, "Date moved only",
 "A.6.2.4 AI system verification and validation; A.6.2.2 requirements and specification; main-body operational planning and control requirement. Intent: define and run V&V against stated criteria.", P,
 "8.29 Security testing in development and acceptance; 8.31 Separation of development, test and production environments.", A,
 "MEASURE 1.1; MEASURE 2.3; MEASURE 2.5; MEASURE 2.6", P,
 "ISO asks you to define V&V criteria but does not require pre-defined probabilistic thresholds or a pre-market gate. Nothing in either framework ties test metrics to the intended purpose in Art. 9(8) terms.",
 "Write acceptance thresholds into the requirements spec (A.6.2.2) BEFORE testing; record them as evidence for Annex IV 2(g).",
 "prEN 18229-2 (accuracy and robustness): drafting."),

("PRV-HR-A09-VULN", "Art. 9(9)",
 "When applying the risk management system, consider whether the system is likely to adversely affect people under 18 and, as appropriate, other vulnerable groups.",
 PRV, HR, HR_DATES, "Date moved only",
 "A.5.4 Assessing AI system impact on individuals or groups of individuals; A.5.2 impact assessment process. Intent: look at effects on specific groups.", P,
 "-", NA,
 "MAP 5.1; MAP 1.1", A,
 "Neither framework names minors or vulnerable groups as a mandatory consideration; ISO A.5.4 is the right place but is generic.",
 "Add an explicit minors/vulnerable-group question to the A.5.2 impact-assessment template.",
 "Covered by prEN 18228 scope (risk management)."),

("PRV-HR-A10-GOV", "Art. 10(1), 10(2)(a)-(e), 10(2)(h)",
 "Apply data governance and management practices to training, validation and testing data: design choices, collection and origin (incl. original purpose of personal data), preparation operations, assumptions, availability/suitability, and identification of data gaps that prevent compliance.",
 PRV, HR, HR_DATES, "Amended: Art. 10(1) now cross-refers to Art. 4a; Art. 10(5) deleted",
 "A.7.2 Data for development and enhancement; A.7.3 Acquisition of data; A.7.4 Quality of data; A.7.5 Data provenance; A.7.6 Data preparation; A.4.3 Data resources. Intent: managed, traceable data lifecycle.", S,
 "5.9 Inventory of information and other associated assets; 5.12 Classification of information.", A,
 "MAP 2.3; MEASURE 2.1", P,
 "'Substantially' applies to the PROCESS. ISO A.7 sets no quality thresholds and is not tied to one system's intended purpose; Art. 10(2)(h) 'data gaps that prevent compliance with this Regulation' is a legal test ISO does not frame.",
 "Produce one data sheet per system (also feeds Annex IV 2(d)); record 10(2)(h) data-gap analysis explicitly.",
 "prEN 18284 (quality and governance of datasets): drafting; Commission comments under review Aug 2026."),

("PRV-HR-A10-BIAS", "Art. 10(2)(f)-(g), 10(3)-(4)",
 "Examine data for biases likely to harm health/safety, affect fundamental rights or cause prohibited discrimination (including feedback-loop bias); detect, prevent and mitigate them; keep data relevant, sufficiently representative and as error-free/complete as possible for the persons and setting concerned.",
 PRV, HR, HR_DATES, "Amended with Art. 10(1)/4a (see PRV-HR-A10-GOV)",
 "A.7.4 Quality of data; A.5.4 Assessing impact on individuals or groups; A.6.2.4 V&V. Intent: data fit for purpose and group-level impact looked at.", P,
 "-", NA,
 "MEASURE 2.11; MAP 2.3", P,
 "Neither names 'prohibited discrimination under Union law' as the test. NIST MEASURE 2.11 is the most direct outcome in any of the three corpora but is evaluative, not a conformity threshold. Note statutory shortcut: Art. 42(1) presumes compliance with 10(4) for systems trained and tested on data reflecting the intended setting.",
 "Document the bias metrics chosen and WHY (NIST 1.2.1 warns metrics can be gamed); keep the Art. 42(1) setting-representativeness evidence.",
 "prEN 18283 (bias management): drafting; WD consultation closed 30 Apr 2026; targeted for enquiry before Oct 2026 plenary."),

("PRV-HR-A10-SCD", "Art. 4a (replacing deleted Art. 10(5))",
 "Exceptionally process special-category personal data for bias detection and correction only if strictly necessary, with no feasible alternative data, re-use limits, state-of-the-art security, controlled access, no onward transfer, prompt deletion, and a record of why it was necessary.",
 PRV, HR, "Applies from 27 Jul 2026 (entry into force of Reg. 2026/1744) per secondary sources; verify against OJ text.",
 "NEW: Art. 10(5) deleted; Art. 4a inserted (secondary sources only - OJ text not directly retrieved)",
 "A.7.3 Acquisition of data. Intent: data is obtained deliberately. Does not address lawful basis for special-category data.", A,
 "5.34 Privacy and protection of PII; 8.3 Information access restriction; 8.10 Information deletion; 8.11 Data masking.", P,
 "MEASURE 2.10", A,
 "Neither AI framework supplies the GDPR Art. 9 analysis. 'Strict necessity' and 'no alternative data' are legal judgements for DPO + counsel. 27001 controls evidence the SECURITY conditions only.",
 "Treat as a DPIA-linked decision record, not a control. Do not claim coverage from ISO 42001.",
 "-"),

("PRV-HR-A11-DOC", "Art. 11, Annex IV",
 "Draw up technical documentation BEFORE placing on the market and keep it current, containing at least the Annex IV elements: description, development process, data sheets, human-oversight assessment, signed test reports, cybersecurity measures, RMS description, change log, list of harmonised standards applied, EU declaration of conformity copy, post-market plan.",
 PRV, HR, HR_DATES, "Amended: simplified Annex IV form extended from SMEs to small mid-caps (SMCs)",
 "A.6.2.7 AI system technical documentation; A.6.2.3 Documentation of design and development; main-body documented-information requirement. Intent: maintain system-level documentation.", P,
 "5.37 Documented operating procedures; 5.33 Protection of records.", A,
 "MAP 2.2; MEASURE 2.1", A,
 "ISO does not prescribe Annex IV content. Specific gaps: list of harmonised standards applied (Annex IV pt 7), copy of EU declaration of conformity (pt 8), post-market plan inclusion (pt 9), dated and signed test reports (2(g)). NIST outcomes are deliberately non-prescriptive on documentation content.",
 "Use Annex IV as the template and treat A.6.2.7 as the process that keeps it current.",
 "None dedicated; EN 18286 touches documentation via QMS (Art. 17(1)(k))."),

("PRV-HR-A12-LOG", "Art. 12(1)-(2) (12(3) for Annex III 1(a))",
 "Design the system so it can technically record events (logs) automatically over its lifetime, sufficient to spot risk situations or substantial modification, support post-market monitoring and enable deployer monitoring.",
 PRV, HR, HR_DATES, "Date moved only",
 "A.6.2.8 AI system recording of event logs. Intent: decide what events are recorded and retain them.", P,
 "8.15 Logging; 8.16 Monitoring activities; 8.17 Clock synchronization.", P,
 "MEASURE 2.4; MANAGE 4.1", A,
 "ISO A.6.2.8 asks the organisation to define logging; Art. 12 is a PRODUCT-DESIGN requirement (the capability must exist in the system). 27001 logging is built for security events, not AI-functioning traceability. 12(3) adds minimum fields for remote biometric identification.",
 "Specify log schema in the requirements spec; verify it supports Art. 72 analysis and Art. 26(5) deployer monitoring.",
 "prEN 18229-1 (logging): enquiry closed 20 Aug 2026, rejected on the weighted population threshold; 443 comments; reconsideration requests due 25 Sep 2026."),
]
