from common import *

ROWS = [
("PRV-HR-A13-IFU", "Art. 13(1)-(3)",
 "Make the system transparent enough for deployers to interpret and use its output, and ship instructions for use covering at least: provider identity, intended purpose, tested accuracy/robustness/cybersecurity levels and what can affect them, foreseeable misuse risks, explainability features, group-level performance, input-data specs, pre-determined changes, oversight measures, resource/lifetime needs and log-collection mechanisms.",
 PRV, HR, HR_DATES, "Date moved only",
 "A.8.2 System documentation and information for users; A.8.5 Information for interested parties; A.6.2.7 Technical documentation. Intent: users get the information needed to use the system properly.", P,
 "-", NA,
 "MAP 2.2; MEASURE 2.9; GOVERN 4.2", P,
 "A.8.2 does not mandate the Art. 13(3) content list: declared accuracy metrics and circumstances that affect them, group-level performance, pre-determined changes, and deployer log-collection mechanisms are the usual omissions.",
 "Build the instructions for use from the Art. 13(3) list, not from the A.8.2 intent summary.",
 "prEN 18229-3 (transparency and human oversight): drafting."),

("PRV-HR-A14-OVS", "Art. 14(1)-(4)",
 "Design the system (with suitable human-machine interface) so natural persons can oversee it: understand its capacities and limits, stay aware of automation bias, interpret output, decide not to use or to override/reverse output, and intervene or stop it in a safe state ('stop' button or equivalent).",
 PRV, HR, HR_DATES, "Date moved only",
 "A.6.1.3 Processes for responsible design and development; A.6.2.2 Requirements and specification; A.3.2 AI roles and responsibilities. Intent: responsible design and defined accountability - no control addresses oversight interface design.", A,
 "-", NA,
 "MAP 3.5; GOVERN 3.2; MANAGE 2.4", P,
 "Art. 14 is a DESIGN requirement (override, stop, automation-bias awareness). ISO 42001 has no control for it. NIST is stronger than ISO here (MAP 3.5, MANAGE 2.4 'supersede, disengage, or deactivate') but still organisational, not a product-design test.",
 "Specify oversight measures as functional requirements and test them; record in Annex IV 2(e).",
 "prEN 18229-3 (transparency and human oversight): drafting."),

("PRV-HR-A15-ACC", "Art. 15(1)-(4)",
 "Achieve and maintain appropriate accuracy and robustness over the lifecycle; declare accuracy metrics in the instructions for use; be resilient to errors, faults and inconsistencies (redundancy / fail-safe); for systems that keep learning, remove or reduce feedback loops that feed biased output back into input.",
 PRV, HR, HR_DATES, "Date moved only",
 "A.6.2.4 AI system verification and validation; A.6.2.6 AI system operation and monitoring. Intent: validate before release, monitor in operation.", P,
 "8.14 Redundancy of information processing facilities; 8.13 Information backup; 8.6 Capacity management.", A,
 "MEASURE 2.5; MEASURE 2.6; MEASURE 2.4", P,
 "Neither framework sets levels; both require you to define and monitor them. Feedback-loop mitigation in continual-learning systems (15(4)) is not explicit in either. NIST 'Valid and Reliable' and 'Safe' characteristics are the closest conceptual fit.",
 "Declare metrics once, in the instructions for use, and trace them to Annex IV 2(g) test reports.",
 "prEN 18229-2 (accuracy and robustness): drafting."),

("PRV-HR-A15-CYB", "Art. 15(5), Art. 42(2)",
 "Be resilient against unauthorised third parties altering use, outputs or performance, with measures against data poisoning, model poisoning, adversarial examples/model evasion, confidentiality attacks and model flaws.",
 PRV, HR, HR_DATES, "Amended: new Art. 42(3) - systems complying with Reg. (EU) 2024/2847 (Cyber Resilience Act) deemed to comply with Art. 15 cybersecurity (secondary source; verify)",
 "A.4.5 System and computing resources; main-body AI risk assessment requirement. Intent: resourcing and risk assessment - no AI-specific security control exists in Annex A.", A,
 "8.8 Management of technical vulnerabilities; 8.25 Secure development life cycle; 8.26 Application security requirements; 8.29 Security testing; 5.7 Threat intelligence; 8.20 Networks security.", P,
 "MEASURE 2.7; MANAGE 3.2", P,
 "A generic ISMS does not name the Art. 15(5) AI-specific attack classes (poisoning, evasion, confidentiality attacks, model flaws). NIST AI RMF text (s.3.3) names them but as characteristics, not as a required test. Art. 42(2) presumption needs a certificate under an EU cybersecurity scheme (Reg. 2019/881) whose reference is published in the OJ.",
 "Extend the 27001 threat model to ML-specific attacks and test them under A.6.2.4. This is where a 27001 + 42001 organisation is strongest.",
 "prEN 18282 (AI cybersecurity): enquiry rejected by national bodies 30 Jul 2026; new scope at ballot to 16 Sep 2026."),

("PRV-HR-A17-QMS", "Art. 17(1)-(4)",
 "Operate a documented quality management system covering 13 aspects: compliance strategy incl. conformity assessment and modification management; design/development control; test and validation; technical specs and standards applied; data management; risk management; post-market monitoring; serious-incident procedures; authority communication; record-keeping; resource management; accountability framework.",
 PRV, HR, HR_DATES, "Amended: Art. 17(2) proportionality extended to small mid-caps (SMCs)",
 "main-body requirements of the AI management system as a whole (policy, documented information and the rest); A.2.2 AI policy; A.3.2 roles; A.6.2.2-A.6.2.8 AI system life-cycle controls; A.10.3 suppliers. Intent: a certified management system around AI development and use.", S,
 "main-body requirements of the parallel ISMS (same management-system structure) - supports integrated management-system operation.", A,
 "GOVERN 1.1; GOVERN 1.2; GOVERN 1.4; GOVERN 1.5; GOVERN 2.1", P,
 "The closest thing to an equivalence in the whole crosswalk, and it is still NOT equivalence. Missing from a stock ISO 42001 AIMS: (a) conformity-assessment/modification strategy, (e) which technical specs and standards apply and what you do where harmonised standards are not used, (i) Art. 73 serious-incident procedure, (j) authority/notified-body communication procedure. A certificate attests to the management system, not to Art. 17 conformity.",
 "Add an 'Art. 17 overlay' to the AIMS for items (a), (e), (i), (j). Watch EN 18286 - it is the standard built for Art. 17 and reportedly includes an Annex D mapping to ISO 42001 controls.",
 "EN 18286:2026 published by CEN-CENELEC in July 2026 (sources differ: 22 and 30 Jul). Not cited in the OJ as of 15 Sep 2026 (latest source), so NO presumption of conformity yet."),

("PRV-HR-A19-LOGRET", "Art. 19",
 "Retain automatically generated logs under the provider's control for a period appropriate to intended purpose and at least six months, unless other Union or national law (notably data protection) says otherwise.",
 PRV, HR, HR_DATES, "Date moved only",
 "A.6.2.8 AI system recording of event logs. Intent: decide log content and keep it.", P,
 "8.15 Logging; 5.33 Protection of records.", P,
 "MANAGE 4.1", A,
 "The six-month floor and the data-protection override are legal parameters; the GDPR storage-limitation tension is for the DPO to resolve, not for a control to evidence.",
 "Record the retention basis per log type, including the GDPR justification.",
 "prEN 18229-1 (logging): see PRV-HR-A12-LOG."),

("PRV-HR-A43-CA", "Art. 43",
 "Before placing on the market, put the system through the required conformity assessment: internal control (Annex VI), or QMS + technical documentation assessed by a notified body (Annex VII), or the sectoral procedure for Annex I products; repeat on substantial modification.",
 PRV, HR, HR_DATES, "Amended: Art. 43(3) revised for sectoral notified bodies (to apply for designation under the Act by 28 Jan 2028 - secondary source; verify)",
 "main-body internal audit and management review requirements (no Annex A control applies). Intent: the organisation audits its own management system.", A,
 "-", NA,
 "MEASURE 1.3; MANAGE 1.1", A,
 "Different object, different issuer, different legal effect: an ISO 42001 certificate attests a management system; Art. 43 assesses THE SYSTEM against Section 2. For Annex III point 1 (biometrics) the Annex VII notified-body route is mandatory where harmonised standards are not applied (Art. 43(1)) - and none is cited in the OJ yet.",
 "Decide Annex VI vs VII per system early; do not present an ISO certificate as a conformity assessment.",
 "prEN 18285 (conformity assessment framework): mature draft 4 Sep 2026, going to the Commission."),

("PRV-HR-A47-DOC", "Art. 47, Annex V",
 "Draw up a written EU declaration of conformity per system (Annex V content), keep it 10 years, give copies to authorities on request. By signing, the provider assumes responsibility for Section 2 compliance.",
 PRV, HR, HR_DATES, "Date moved only",
 "-", N,
 "-", NA,
 "-", N,
 "A legal act with legal consequences (47(4)). No management-system standard or voluntary framework produces it.",
 "Template it from Annex V; sign only after the conformity assessment completes.",
 "-"),

("PRV-HR-A48-CE", "Art. 48",
 "Affix the CE marking (digital CE marking for digitally provided systems), followed by the notified-body number where one was involved.",
 PRV, HR, HR_DATES, "Date moved only",
 "-", N,
 "-", NA,
 "-", N,
 "Statutory marking; outside the scope of every voluntary framework.",
 "Operational/legal step after Art. 47.",
 "-"),

("PRV-HR-A49-REG", "Art. 49(1), 49(5)",
 "Register the provider and the system in the EU database before placing on the market (national-level registration for Annex III point 2 critical infrastructure).",
 PRV, HR, HR_DATES, "Date moved only",
 "A.4.2 Resource documentation. Intent: know what resources/systems you have - not a regulatory registration.", A,
 "5.9 Inventory of information and other associated assets.", A,
 "GOVERN 1.6", A,
 "An internal AI-system inventory is a prerequisite for registration but is not registration.",
 "Keep the inventory fields aligned to Annex VIII so registration is an export, not a project.",
 "-"),

("PRV-HR-A06-NONHR", "Art. 6(3)-(4), Art. 49(2)",
 "If you conclude an Annex III system is NOT high-risk (e.g. narrow procedural task), document that assessment BEFORE placing on the market, register the system under Art. 49(2), and produce the assessment on request. Profiling of natural persons is always high-risk.",
 PRV, HR, "Art. 6(3)-(4): applies with the high-risk regime (2 Dec 2027); registration obligation retained", "Registration obligation retained despite earlier proposal to remove it (Cooley, secondary source); Commission Art. 6 guidelines draft published 19 May 2026 (Mayer Brown, secondary)",
 "A.5.2 AI system impact assessment process. Intent: assess an AI system's impacts - no classification step exists in ISO 42001.", A,
 "-", NA,
 "MAP 1.1; MAP 2.1", A,
 "Classification is a legal determination. Neither framework has an Act-aligned classification step; a wrong 'not high-risk' conclusion is itself the exposure.",
 "Keep a dated classification memo per system; revisit on any intended-purpose change (Art. 25(1)(c)).",
 "-"),
]
