from common import *

ROWS = [
("PRV-HR-A20-CORR", "Art. 20",
 "If you have reason to think a placed system is non-conforming, immediately take corrective action (bring into conformity, withdraw, disable or recall) and inform distributors, deployers, authorised representative and importers; if it presents a risk (Art. 79(1)), investigate with the deployer and inform market surveillance authorities and any notified body.",
 PRV, HR, HR_DATES, "Date moved only",
 "main-body nonconformity and corrective-action requirement; A.8.4 Communication of incidents; A.6.2.6 Operation and monitoring. Intent: fix and learn from nonconformities and incidents.", P,
 "5.26 Response to information security incidents; 5.27 Learning from information security incidents.", A,
 "MANAGE 2.3; MANAGE 2.4; MANAGE 4.3", P,
 "ISO corrective action is raised against the management system; Art. 20 is triggered by non-conformity with the REGULATION and requires a real withdraw/disable/recall capability plus notification of authorities. 'Immediately' has no ISO equivalent.",
 "Pre-build the withdraw/disable runbook and the authority-notification template (ties to PRV-HR-A73-SI).",
 "-"),

("PRV-HR-A72-PMM", "Art. 72",
 "Establish and document a post-market monitoring system, proportionate to the technology and risk, based on a plan that forms part of the technical documentation; actively collect, document and analyse performance data over the system's lifetime to evaluate CONTINUOUS COMPLIANCE with Section 2, including interaction with other AI systems.",
 PRV, HR, HR_DATES, "Date moved only. Commission template implementing act was due 2 Feb 2026 - verify whether adopted.",
 "A.6.2.6 AI system operation and monitoring; main-body monitoring/measurement and continual-improvement requirements. Intent: monitor operation and improve.", P,
 "8.16 Monitoring activities.", A,
 "MEASURE 2.4; MEASURE 3.1; MANAGE 4.1; MANAGE 4.2", P,
 "NIST MANAGE 4.1 is the closest single outcome in any corpus, but neither framework frames monitoring as evaluating continuous compliance with the Section 2 requirements, and neither requires the plan to sit inside the technical documentation or to follow the Commission template.",
 "Define monitoring KPIs as Section 2 compliance indicators (accuracy drift, log completeness, oversight overrides), not just performance.",
 "-"),

("PRV-HR-A73-SI", "Art. 73(1)-(6); Art. 3(49)",
 "Report any serious incident to the market surveillance authority of the Member State where it occurred: immediately once a causal link (or reasonable likelihood) is established and in any event within 15 days of awareness; 2 days for widespread infringement or critical-infrastructure disruption; 10 days for a death; an incomplete initial report is allowed. Investigate, assess risk and do not alter the system before informing authorities.",
 PRV, HR, HR_DATES, "Date moved only. Commission guidance was due 2 Aug 2025 (Art. 73(7)) - verify it was issued.",
 "A.8.4 Communication of incidents; A.8.3 External reporting; main-body corrective-action requirement. Intent: communicate incidents to the right parties.", P,
 "5.24 Incident management planning and preparation; 5.25 Assessment and decision on events; 5.26 Response; 5.27 Learning; 5.5 Contact with authorities.", P,
 "MANAGE 4.3; GOVERN 4.3", P,
 "An ISO 'incident' is not an Act 'serious incident' (death/serious health harm; critical-infrastructure disruption; infringement of fundamental-rights obligations under Union law; serious property/environment harm). The 15/10/2 day clocks and the no-alteration rule are not in any framework. Expect overlap with GDPR 72h and NIS2 clocks.",
 "Add an 'Art. 3(49) classification' triage step and the three clocks to the incident procedure.",
 "-"),

("PRV-HR-A25-CHAIN", "Art. 25(1)-(4)",
 "Any distributor, importer, deployer or third party becomes the PROVIDER (with all Art. 16 duties) if it puts its name/trademark on a high-risk system, makes a substantial modification, or changes the intended purpose of a non-high-risk system (incl. a general-purpose AI system) so that it becomes high-risk. Suppliers of components/tools must agree in writing what information and technical access the provider needs.",
 PRV, HR, HR_DATES, "Amended: Art. 25(2) initial-provider cooperation duty restated (secondary source; verify)",
 "A.10.2 Allocating responsibilities; A.10.3 Suppliers; A.10.4 Customers. Intent: responsibilities across the supply chain are defined and supplier requirements are managed.", P,
 "5.19 Information security in supplier relationships; 5.20 Addressing information security within supplier agreements; 5.21 Managing information security in the ICT supply chain; 5.22 Monitoring, review and change management of supplier services.", P,
 "GOVERN 6.1; MAP 4.1; MANAGE 3.1", P,
 "ISO A.10 evidences allocation and supplier management, but does not test the Art. 25(1) trigger: a deployer that rebrands or re-purposes a GPAI system for an Annex III use inherits full provider duties. That is the commonly missed exposure.",
 "Add a 'would this change make us the provider?' gate to change management and to every procurement of a GPAI-based system.",
 "-"),

("PRV-HR-A22-AR", "Art. 22",
 "A provider established outside the EU must, before making a high-risk system available in the Union, appoint by written mandate an EU-established authorised representative with the Art. 22(3) tasks.",
 PRV, HR, HR_DATES, "Date moved only",
 "-", N,
 "-", NA,
 "-", N,
 "A statutory appointment; no framework contains an equivalent.",
 "Contract and mandate wording to follow Art. 22(3)(a)-(e).",
 "-"),

("PRV-ALL-A04-LIT", "Art. 4",
 "Providers take measures to support the AI literacy of staff and others operating or using AI systems on their behalf, in light of their knowledge, context of use and the people the systems are used on.",
 PRV, "All AI systems (horizontal, Chapter I; outside the HR/GPAI scope boundary but included because it binds every provider)", "Applied from 2 Feb 2025",
 "Amended: duty changed from 'ensure, to their best extent, a sufficient level' to 'take measures to support the development of' AI literacy; Commission/Member States to support (Reg. 2026/1744; verify OJ text and application date)",
 "main-body competence and awareness requirements; A.4.6 Human resources; A.3.2 AI roles and responsibilities. Intent: people doing AI work are competent and aware.", S,
 "6.3 Information security awareness, education and training.", A,
 "GOVERN 2.2; MAP 3.4", P,
 "The softened wording makes the ISO competence/awareness clauses a good fit. Residual: Art. 4 also reaches 'other persons dealing with the operation and use of AI systems on their behalf' (contractors), and ISO competence is scoped to persons affecting AIMS performance.",
 "Extend the training record to contractors and to affected-persons context.",
 "-"),

("DEP-ALL-A04-LIT", "Art. 4",
 "Deployers take measures to support the AI literacy of staff and others operating or using AI systems on their behalf.",
 DEP, "All AI systems (horizontal, Chapter I)", "Applied from 2 Feb 2025",
 "Amended as PRV-ALL-A04-LIT",
 "main-body competence and awareness requirements; A.9.2 Processes for responsible use of AI systems; A.4.6 Human resources.", S,
 "6.3 Information security awareness, education and training.", A,
 "GOVERN 2.2; MAP 3.4", P,
 "As provider row. Deployer-specific: literacy must cover how to interpret THIS system's output (ties to Art. 14(4) and Art. 26(2)).",
 "Tie training content to the provider's instructions for use.",
 "-"),
]
