from common import *

ROWS = [
("DEP-HR-A26-USE", "Art. 26(1)",
 "Take appropriate technical and organisational measures to use the high-risk system in accordance with the provider's instructions for use.",
 DEP, HR, HR_DATES, "Date moved only",
 "A.9.2 Processes for responsible use of AI systems; A.9.3 Objectives for responsible use; A.9.4 Intended use of the AI system. Intent: use is governed, bounded to intended use and measured against objectives.", S,
 "5.10 Acceptable use of information and other associated assets; 5.37 Documented operating procedures.", A,
 "MAP 3.3; GOVERN 1.2; MANAGE 2.2", P,
 "ISO A.9 is the best organisation-level fit for a deployer. Residual: the benchmark is the PROVIDER'S instructions for use (Art. 13) - a certificate does not show you obtained, read and operationalised them.",
 "Keep a per-system register of instructions-for-use versions and the internal procedure each one drives.",
 "-"),

("DEP-HR-A26-OVS", "Art. 26(2)",
 "Assign human oversight to natural persons who have the necessary competence, training, authority and support.",
 DEP, HR, HR_DATES, "Date moved only",
 "A.3.2 AI roles and responsibilities; A.4.6 Human resources; A.9.2; cl. 7.2 Competence. Intent: named, competent, resourced people.", P,
 "5.2 Information security roles and responsibilities; 6.3 Awareness, education and training.", A,
 "GOVERN 3.2; GOVERN 2.1; GOVERN 2.3; MAP 3.5", P,
 "'Authority' (the power to override) is the element usually missing in practice and is not a control requirement in either framework. NIST GOVERN 3.2 (differentiating human-AI configuration roles) is the closer outcome.",
 "Document override authority in the role description, not only competence.",
 "-"),

("DEP-HR-A26-INPUT", "Art. 26(4)",
 "To the extent the deployer controls input data, ensure it is relevant and sufficiently representative for the system's intended purpose.",
 DEP, HR, HR_DATES, "Date moved only",
 "A.9.2 Processes for responsible use; A.7.4 Quality of data (development-oriented). Intent: data quality governance.", P,
 "-", NA,
 "MAP 2.3", A,
 "ISO Annex A data controls (A.7) are written around development data, not live operational inputs. Representativeness for the intended purpose is not tested.",
 "Add input-data checks to the deployer's operating procedure.",
 "-"),

("DEP-HR-A26-MON", "Art. 26(5)",
 "Monitor operation on the basis of the instructions for use; where use may present a risk (Art. 79(1)), inform provider/distributor and the market surveillance authority without undue delay and SUSPEND use; for a serious incident, inform first the provider, then importer/distributor and authorities immediately.",
 DEP, HR, HR_DATES, "Date moved only",
 "A.6.2.6 Operation and monitoring; A.8.4 Communication of incidents; A.9.2. Intent: watch operation, escalate incidents.", P,
 "5.24-5.27 Incident management; 8.16 Monitoring activities.", P,
 "MEASURE 2.4; MANAGE 4.1; MANAGE 4.3; MANAGE 2.4", P,
 "The suspend-use duty and the reporting sequence (provider first) are specific legal steps. If the provider cannot be reached, Art. 73 applies mutatis mutandis to the deployer.",
 "Pre-authorise the person who can suspend use; script the notification order.",
 "-"),

("DEP-HR-A26-WORK", "Art. 26(7)",
 "Before putting into service or using a high-risk system at the workplace, employer-deployers inform workers' representatives and the affected workers that they will be subject to it.",
 DEP, HR, HR_DATES, "Date moved only",
 "A.8.5 Information for interested parties. Intent: communicate to interested parties.", A,
 "-", NA,
 "GOVERN 5.1", A,
 "Collective-information rules sit in national labour law (works councils, consultation). Frameworks do not cover them.",
 "Involve HR and employment counsel per Member State.",
 "-"),

("DEP-HR-A26-NOTIFY", "Art. 26(11)",
 "Deployers of Annex III systems that make or assist decisions about natural persons must inform those persons that they are subject to the high-risk system.",
 DEP, HR, HR_DATES, "Date moved only",
 "A.8.5 Information for interested parties; A.8.2 System documentation and information for users. Intent: tell the people affected.", P,
 "-", NA,
 "MEASURE 3.3; MAP 5.2", A,
 "Content, timing and format of the notice are legal choices; ISO intent is generic.",
 "Align with GDPR Art. 13/14/22 notices to avoid inconsistent statements.",
 "-"),

("DEP-HR-A27-FRIA", "Art. 27",
 "Before first use, certain deployers (public-law bodies, private entities providing public services, and deployers of Annex III 5(b) credit-scoring and 5(c) life/health-insurance systems) assess impact on fundamental rights: processes, duration/frequency, affected groups, specific harms, human-oversight implementation, remedies and complaint mechanisms; notify the market surveillance authority with the AI Office template; update when facts change.",
 DEP, HR, HR_DATES, "Amended: Art. 27(4) deployers may cross-reference existing DPIAs (secondary source; verify OJ text)",
 "A.5.2 AI system impact assessment process; A.5.3 Documentation of impact assessments; A.5.4 Impact on individuals or groups; cl. 6.1.4 / 8.4 AI system impact assessment. Intent: assess and document effects on individuals, groups and society.", S,
 "5.34 Privacy and protection of PII (DPIA interface).", A,
 "MAP 5.1; MAP 5.2; MAP 1.1; GOVERN 5.1", P,
 "Best conceptual match in the crosswalk (ISO treats impact on individuals as first-class), yet: Art. 27 has a prescribed content list (a)-(f), a scoping rule (who must do it), and a notification-to-authority step with a template. Also: FRIA measures rights, not organisational impact - the register keeps these separate (see /register/).",
 "Use the Art. 27(1)(a)-(f) list as the A.5.3 template; add the authority notification step.",
 "-"),

("DEP-HR-A86-EXPL", "Art. 86",
 "A person affected by a deployer's decision based on output of an Annex III high-risk system (excluding point 2) that has legal or similarly significant adverse effects can obtain clear, meaningful explanations of the AI system's role and the main elements of the decision.",
 DEP, HR, HR_DATES, "Date moved only",
 "A.8.5 Information for interested parties; A.5.4 Assessing impact on individuals or groups. Intent: communicate with and consider affected people.", A,
 "-", NA,
 "MEASURE 2.9; MEASURE 3.3", A,
 "An individually enforceable right. Needs a request-handling process and explanation capability; NIST MEASURE 2.9 is about explaining the model for governance, not answering an individual.",
 "Build an explanation-request workflow and measure turnaround.",
 "-"),

("IMP-HR-A23-VERIFY", "Art. 23",
 "Before placing a non-EU provider's high-risk system on the market, verify the conformity assessment was done, technical documentation exists, CE marking + EU declaration + instructions for use are present and an authorised representative was appointed; do not place if non-conforming; keep copies 10 years; cooperate with authorities.",
 IMP, HR, HR_DATES, "Date moved only",
 "A.10.3 Suppliers; A.10.2 Allocating responsibilities. Intent: manage what you take in from suppliers.", A,
 "5.19-5.22 Supplier controls.", A,
 "GOVERN 6.1; MANAGE 3.1", A,
 "Importer verification is a legal gate with named documents, not a supplier-assurance process.",
 "Turn Art. 23(1)(a)-(d) into a pre-import checklist.",
 "-"),

("DIS-HR-A24-VERIFY", "Art. 24",
 "Before making a high-risk system available, verify CE marking, EU declaration, instructions for use and that provider/importer met their duties; do not supply if non-conforming; take or ensure corrective action; inform authorities where Art. 79(1) risk.",
 DIS, HR, HR_DATES, "Date moved only",
 "A.10.2 Allocating responsibilities; A.10.4 Customers. Intent: responsibilities and customer relationships are defined.", A,
 "-", NA,
 "GOVERN 6.1", A,
 "As importer: a legal verification gate, not a supplier-management control.",
 "Distributor checklist from Art. 24(1)-(2).",
 "-"),
]
