from common import *

GP_OM = "Substantive duties unchanged by Reg. 2026/1744 per secondary sources; AI Office exclusive competence expanded over AI systems built on a provider's own GPAI model"

ROWS = [
("GPP-GP-A53-DOC", "Art. 53(1)(a), Annex XI s.1",
 "Draw up and keep current technical documentation of the GPAI model (training and testing process, evaluation results; Annex XI items incl. architecture, parameters, data provenance and curation, training compute, energy consumption), to give to the AI Office and national authorities on request. Free and open-source models are exempt unless they carry systemic risk (Art. 53(2)).",
 GPP, GP, GPAI_DATES, GP_OM,
 "A.6.2.7 AI system technical documentation; A.6.2.3 Documentation of design and development; A.7.5 Data provenance. Intent: maintain design-level documentation and data lineage.", P,
 "-", NA,
 "MAP 2.2; MEASURE 2.1", A,
 "ISO control is system-oriented; Annex XI is MODEL-oriented (training compute in FLOPs, energy consumption, number of data points). Neither framework asks for energy or compute reporting.",
 "Build the Annex XI sheet as a model card variant and keep it with the model release.",
 "-"),

("GPP-GP-A53-DOWN", "Art. 53(1)(b), Annex XII",
 "Make information and documentation available to downstream AI-system providers so they understand the model's capabilities and limits and can meet their own obligations (Annex XII: tasks, acceptable-use policy, architecture, modalities, maximum input size, data information, integration means).",
 GPP, GP, GPAI_DATES, GP_OM,
 "A.8.2 System documentation and information for users; A.8.5 Information for interested parties; A.10.4 Customers. Intent: users and customers get what they need to use the system properly.", P,
 "-", NA,
 "MAP 2.2; GOVERN 6.1", A,
 "Annex XII content list (acceptable use policy, context-window size, integration means) is not in ISO A.8.2. This is the information a downstream provider needs for Art. 25 and Art. 13 - gaps here propagate down the chain.",
 "Publish a downstream pack versioned against model releases.",
 "-"),

("GPP-GP-A53-COPY", "Art. 53(1)(c)",
 "Put in place a policy to comply with Union copyright law, in particular to identify and honour rights reservations expressed under Art. 4(3) of Directive (EU) 2019/790 (including by state-of-the-art technologies).",
 GPP, GP, GPAI_DATES, GP_OM,
 "A.7.3 Acquisition of data; A.7.5 Data provenance. Intent: data is acquired deliberately and traceable. Does not address copyright reservations.", A,
 "5.32 Intellectual property rights.", A,
 "GOVERN 6.1; MAP 4.1", A,
 "Honouring machine-readable opt-outs is a specific technical-legal duty. NIST GOVERN 6.1 / MAP 4.1 mention third-party IP infringement risk, which is related but not the Art. 4(3) mechanism.",
 "Document the crawler/opt-out handling and the evidence that it ran.",
 "-"),

("GPP-GP-A53-SUMM", "Art. 53(1)(d)",
 "Draw up and publish a sufficiently detailed summary of the content used to train the model, using the AI Office template.",
 GPP, GP, GPAI_DATES, GP_OM,
 "A.7.5 Data provenance. Intent: internal provenance records - not a public summary.", A,
 "-", NA,
 "-", N,
 "A PUBLIC disclosure duty. Internal provenance records are an input, not the deliverable. Check the AI Office template version currently in force before publishing.",
 "Generate the public summary from the provenance records and review it with counsel.",
 "-"),

("GPP-GP-A53-ROUTE", "Art. 53(4), Art. 55(2)",
 "Demonstrate compliance through an approved code of practice (until a harmonised standard is published), OR through a harmonised standard (presumption of conformity), OR through alternative adequate means assessed by the Commission.",
 GPP, GP, GPAI_DATES, GP_OM + ". A voluntary GPAI Code of Practice exists (referenced in secondary sources); verify whether the Commission approved it by implementing act under Art. 56(6).",
 "-", N,
 "-", NA,
 "-", N,
 "The GPAI equivalent of the high-risk headline finding: ISO 42001 certification is not one of the three routes the Act names. Without a code or an OJ-cited harmonised standard, the provider carries the burden of showing 'alternative adequate means'.",
 "Decide the compliance route explicitly and record the reasoning.",
 "No GPAI-specific harmonised standard identified in the JTC 21 tracker used here."),

("GPP-GP-A54-AR", "Art. 54",
 "A third-country GPAI provider appoints by written mandate an EU-established authorised representative before placing the model on the Union market (not for open-source models without systemic risk).",
 GPP, GP, GPAI_DATES, GP_OM,
 "-", N,
 "-", NA,
 "-", N,
 "Statutory appointment; no framework equivalent.",
 "Mandate wording from Art. 54(3)(a)-(d).",
 "-"),

("GPP-GPS-A55-EVAL", "Art. 55(1)(a), Annex XI s.2",
 "For systemic-risk models: perform model evaluation with standardised protocols and tools reflecting the state of the art, including documented adversarial testing to identify and mitigate systemic risks.",
 GPP, GPS, GPAI_DATES, GP_OM,
 "A.6.2.4 AI system verification and validation. Intent: validate against requirements - no adversarial/red-team element.", A,
 "8.29 Security testing in development and acceptance.", A,
 "MEASURE 2.7; MEASURE 1.3; MEASURE 2.5", P,
 "Documented adversarial testing is not an ISO 42001 control. NIST names security/resilience evaluation and independent assessors but not adversarial testing of frontier-scale models as a requirement.",
 "Keep red-team scope, method and results as Annex XI s.2 evidence.",
 "-"),

("GPP-GPS-A55-SYS", "Art. 55(1)(b)",
 "Assess and mitigate possible systemic risks at Union level, including their sources, arising from development, placing on the market or use of the model.",
 GPP, GPS, GPAI_DATES, GP_OM,
 "main-body AI risk assessment and AI system impact assessment requirements; A.5.5 Assessing societal impacts of AI systems. Intent: assess societal-level impacts.", P,
 "-", NA,
 "MAP 5.1; MEASURE 3.1; MANAGE 1.2; MANAGE 1.3", P,
 "'Systemic risk' (Art. 3(65)) is specific to high-impact capabilities with Union-level reach. An organisation-scoped risk assessment will not, by default, be scoped to that.",
 "Add a Union-level systemic-risk register section with named sources.",
 "-"),

("GPP-GPS-A55-INC", "Art. 55(1)(c)",
 "Track, document and report without undue delay to the AI Office (and, as appropriate, national authorities) serious incidents and possible corrective measures.",
 GPP, GPS, GPAI_DATES, GP_OM,
 "A.8.4 Communication of incidents; A.8.3 External reporting; main-body corrective-action requirement. Intent: tell the right parties about incidents.", P,
 "5.24-5.27 Incident management; 5.5 Contact with authorities.", P,
 "MANAGE 4.3; GOVERN 4.3", P,
 "No time limit is given in Art. 55(1)(c) ('without undue delay'), unlike the 15/10/2 day clocks in Art. 73 for high-risk providers. The Act's 'serious incident' definition applies (Art. 3(49)).",
 "Share one incident pipeline across Art. 73 and Art. 55 with the two reporting recipients.",
 "-"),

("GPP-GPS-A55-CYB", "Art. 55(1)(d)",
 "Ensure an adequate level of cybersecurity protection for the systemic-risk model and the physical infrastructure of the model.",
 GPP, GPS, GPAI_DATES, GP_OM,
 "A.4.5 System and computing resources. Intent: resourcing - not a security control.", A,
 "5.x Organizational, 7.x Physical and 8.x Technological controls as a set; 8.24 Use of cryptography; 8.3 Information access restriction; 7.1 Physical security perimeters.", S,
 "MEASURE 2.7", P,
 "The ISMS is the strongest evidence here, but only if its SCOPE statement actually includes model weights, training pipelines and the compute estate - scope is chosen by the organisation and is routinely drawn around corporate IT.",
 "Check the 27001 Statement of Applicability and scope explicitly cover the model assets.",
 "-"),
]
